CREATE DATABASE facturas;

use facturas;

CREATE TABLE clientes(
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(255) NOT NULL,
  Nombre VARCHAR(255) NOT NULL,
  Nombre VARCHAR(255) NOT NULL,
  Edad int(4),
  CURP VARCHAR(19) NOT NULL,
  RFC VARCHAR(19) NOT NULL,
  FechaRegistro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

